Bump Inja to latest version
solo-io/envoy-gloo pull request #243
Opened 2023-06-08 14:36 UTC by jbohanon

This will include newer template features such as "set"

2023-06-21 20:39 UTC, jbohanon commented on bazel/repository_locations.bzl
> +        commit = "ddb94b9d031790282f87e51f7e59a9cd61e8e55b",
```suggestion
        # envoy 1.26.2
        commit = "4aa28dcbfdaf17b754ee6d4ca4f1fdf6f84c99dc",
```

2023-06-22 13:18 UTC, ben-taussig-solo commented on source/extensions/filters/http/transformation/inja_transformer.cc
> +  absl::optional<std::string> string_body;
Does this get used?

2023-06-22 19:58 UTC, jbohanon commented on source/extensions/filters/http/transformation/inja_transformer.cc
> +  TransformerInstance instance(*header_map, header_map, get_body,
Good call; I reordered the definitions

2023-06-22 19:58 UTC, jbohanon commented on source/extensions/filters/http/transformation/inja_transformer.cc
> +  absl::optional<std::string> string_body;
Nope! Good catch; removed

2023-06-22 20:59 UTC, yuval-k requested changes
I mentioned this on slack, but for reference - i think we can use the old structure where most things are initialized in the ctor. To make this work with the new inja, we'll need to use envoy's ThreadLocal to temporary store the per-request template context ; that way the callbacks would be registered only once, at ctor time. and will get the different context via the TLS.

2023-06-23 18:38 UTC, jbohanon commented
Closing in favor of https://github.com/solo-io/envoy-gloo/pull/248

2023-06-23 18:38 UTC, closed without merging